Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"

    config.vm.hostname = "user-1"
    config.vm.provision 'shell', inline: <<-SHELL
        useradd newberdi &>/dev/null
        echo "newberdi:123123" | chpasswd
        usermod -aG adm newberdi
        timedatectl set-timezone Asia/Yekaterinburg
        SHELL

    config.vm.provider "virtualbox" do |vb|
        vb.name = "newberdi-vm"
        vb.cpus = 2
        vb.memory = 4096
    end
end